---
title: "Article 1"
author: "Nishtha Arora"
date: "2023-04-04"
output: html_document
---
HEADLINE: What a suicide registry database should look like

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(readr)
```

Data from WHO- https://www.who.int/data/gho/data/themes/mental-health/suicide-rates

```{r}

library(tidyverse)
data <- data <- read_csv("data/Article-wise/data.csv") %>% 
  select(SpatialDimValueCode, Location, Period, Dim1, FactValueNumeric) %>% 
  filter(Dim1 == "Both sexes") 
```

## Countries with outliers in data

```{r}
new <- data %>% filter(Location == "Kiribati")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Central African Republic")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Latvia")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Republic of Korea")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
names <- unique(data$Location)
view(names)
```

```{r}
new <- data %>% filter(Location == "Fiji")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Rwanda")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Poland")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Comoros")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Uzbekistan")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Bosnia and Herzegovina")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Grenada")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Niger")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Cuba")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Equatorial Guinea")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Burkina Faso")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Samoa")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Latvia")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Sao Tome and Principe")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Honduras")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Lebanon")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Maldives")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Republic of Korea")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Bahamas")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Timor-Leste")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Iraq")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Timor-Leste")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Dominican Republic")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Iran (Islamic Republic of)")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Brazil")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Bolivia (Plurinational State of)")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "The former Yugoslav Republic of Macedonia")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Portugal")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Belize")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Serbia")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Mali")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Argentina")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "United Republic of Tanzania")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Democratic People's Republic of Korea")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Bosnia and Herzegovina")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Uzbekistan")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Comoros")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Poland")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

```{r}
new <- data %>% filter(Location == "Rwanda")
boxplot(new$FactValueNumeric
        ,
  ylab = "hwy"
)
```

