---
title: "Map"
author: "Nishtha Arora"
date: "2023-03-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

Data sources: https://data.gov.in/catalog/stateut-wise-distribution-suicides-causes
http://www.diva-gis.org/datadown

# Initial Analysis 3

## 2014 statewise and Union terr India suicide rate

```{r libraries}
library(readr)
library(tidyverse)
library(readxl)
library(lubridate)
```

```{r}
library(readxl)
datafile <- read_excel("data/map/datafile.xls") %>% 
  select(`States/UTs`, `Grand Total`) %>% 
  group_by(`States/UTs`) %>% 
  summarise(Average_suicide_rate= mean(`Grand Total`)) %>% 
  slice(-c(33,34,35))
datafile$id <- seq.int(nrow(datafile))
```

```{r}
library(ggplot2)
library(RColorBrewer)
library(ggmap)
library(maps)
# library(rgdal)
# library(scales)
library(maptools)
# library(gridExtra)
library(rgeos)
```


```{r}
states_shape = readShapeSpatial("data/map/IND_adm/IND_adm1.shp")
class(states_shape)
names(states_shape)
print(states_shape$ID_1)
print(states_shape$NAME_1)
#plot(states_shape, main = "Administrative Map of India")
```

```{r}
fortify_shape = fortify(states_shape, region = "ID_1")
class(fortify_shape)
```

```{r}
Merged_data = merge(fortify_shape, datafile, by="id", all.x=TRUE)
Map_plot = Merged_data[order(Merged_data$order), ]
```

```{r}
library(mapproj)
```

```{r}
ggplot() +
  geom_polygon(data = Map_plot,
           	aes(x = long, y = lat, group = group, fill = Average_suicide_rate),
      	     color = "black", linewidth = 0.25) +
  coord_map()+
  scale_fill_gradient(name="Suicide Rate", low = 'white', high = 'red')+
  labs(title="Region-wise 2014 data:India")+
  xlab('Longitude')+
  ylab('Latitude')
  # geom_text(data=cnames, aes(long, lat, label = id), size=3, fontface="bold")
```

